package trillas.mx.pojos;
// Generated 19/09/2016 11:13:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Authorbluvista generated by hbm2java
 */
public class Authorbluvista  implements java.io.Serializable {


     private Integer idAuthorBluvista;
     private String authorBluvista;
     private String authorBook;
     private Set pseudonyms = new HashSet(0);

    public Authorbluvista() {
    }

	
    public Authorbluvista(String authorBluvista) {
        this.authorBluvista = authorBluvista;
    }
    public Authorbluvista(String authorBluvista, String authorBook, Set pseudonyms) {
       this.authorBluvista = authorBluvista;
       this.authorBook = authorBook;
       this.pseudonyms = pseudonyms;
    }
   
    public Integer getIdAuthorBluvista() {
        return this.idAuthorBluvista;
    }
    
    public void setIdAuthorBluvista(Integer idAuthorBluvista) {
        this.idAuthorBluvista = idAuthorBluvista;
    }
    public String getAuthorBluvista() {
        return this.authorBluvista;
    }
    
    public void setAuthorBluvista(String authorBluvista) {
        this.authorBluvista = authorBluvista;
    }
    public String getAuthorBook() {
        return this.authorBook;
    }
    
    public void setAuthorBook(String authorBook) {
        this.authorBook = authorBook;
    }
    public Set getPseudonyms() {
        return this.pseudonyms;
    }
    
    public void setPseudonyms(Set pseudonyms) {
        this.pseudonyms = pseudonyms;
    }




}


