package trillas.mx.pojos;
// Generated 19/09/2016 11:13:12 AM by Hibernate Tools 4.3.1



/**
 * Authorproduction generated by hbm2java
 */
public class Authorproduction  implements java.io.Serializable {


     private Integer idAuthorProduction;
     private String nameAuthorProduction;
     private String nameBook;
     private Integer idCorrespondence;

    public Authorproduction() {
    }

	
    public Authorproduction(String nameAuthorProduction, String nameBook) {
        this.nameAuthorProduction = nameAuthorProduction;
        this.nameBook = nameBook;
    }
    public Authorproduction(String nameAuthorProduction, String nameBook, Integer idCorrespondence) {
       this.nameAuthorProduction = nameAuthorProduction;
       this.nameBook = nameBook;
       this.idCorrespondence = idCorrespondence;
    }
   
    public Integer getIdAuthorProduction() {
        return this.idAuthorProduction;
    }
    
    public void setIdAuthorProduction(Integer idAuthorProduction) {
        this.idAuthorProduction = idAuthorProduction;
    }
    public String getNameAuthorProduction() {
        return this.nameAuthorProduction;
    }
    
    public void setNameAuthorProduction(String nameAuthorProduction) {
        this.nameAuthorProduction = nameAuthorProduction;
    }
    public String getNameBook() {
        return this.nameBook;
    }
    
    public void setNameBook(String nameBook) {
        this.nameBook = nameBook;
    }
    public Integer getIdCorrespondence() {
        return this.idCorrespondence;
    }
    
    public void setIdCorrespondence(Integer idCorrespondence) {
        this.idCorrespondence = idCorrespondence;
    }




}


