package trillas.mx.pojos;
// Generated 19/09/2016 02:39:09 PM by Hibernate Tools 4.3.1



/**
 * Bookauthor generated by hbm2java
 */
public class Bookauthor  implements java.io.Serializable {


     private Integer idBookAuthor;
     private Authorproduction authorproduction;
     private Book book;
     private Integer idRealAuthor;

    public Bookauthor() {
    }

	
    public Bookauthor(Authorproduction authorproduction, Book book) {
        this.authorproduction = authorproduction;
        this.book = book;
    }
    public Bookauthor(Authorproduction authorproduction, Book book, Integer idRealAuthor) {
       this.authorproduction = authorproduction;
       this.book = book;
       this.idRealAuthor = idRealAuthor;
    }
   
    public Integer getIdBookAuthor() {
        return this.idBookAuthor;
    }
    
    public void setIdBookAuthor(Integer idBookAuthor) {
        this.idBookAuthor = idBookAuthor;
    }
    public Authorproduction getAuthorproduction() {
        return this.authorproduction;
    }
    
    public void setAuthorproduction(Authorproduction authorproduction) {
        this.authorproduction = authorproduction;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public Integer getIdRealAuthor() {
        return this.idRealAuthor;
    }
    
    public void setIdRealAuthor(Integer idRealAuthor) {
        this.idRealAuthor = idRealAuthor;
    }




}


