package trillas.mx.pojos;
// Generated 19/09/2016 02:39:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Integer idBook;
     private String title;
     private Set bookauthors = new HashSet(0);

    public Book() {
    }

    public Book(String title, Set bookauthors) {
       this.title = title;
       this.bookauthors = bookauthors;
    }
   
    public Integer getIdBook() {
        return this.idBook;
    }
    
    public void setIdBook(Integer idBook) {
        this.idBook = idBook;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getBookauthors() {
        return this.bookauthors;
    }
    
    public void setBookauthors(Set bookauthors) {
        this.bookauthors = bookauthors;
    }




}


